# Generated by Django 2.2.6 on 2019-10-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.FileField(default='/static/images/icon.png', upload_to='static/uploads'),
            preserve_default=False,
        ),
    ]
