# Generated by Django 2.2.6 on 2019-12-29 23:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191229_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.FileField(default=django.utils.timezone.now, upload_to='static/uploads'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
