# Generated by Django 2.2.6 on 2019-12-30 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20191229_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recipe',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('photo', models.FileField(upload_to='static/uploads/recipes')),
                ('desc', models.TextField()),
                ('serv', models.IntegerField()),
                ('prep', models.IntegerField()),
                ('cook', models.IntegerField()),
                ('ingre', models.TextField()),
                ('instr', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
