# Generated by Django 2.2.6 on 2019-12-30 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191229_2047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
