# Generated by Django 2.2.6 on 2020-01-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_delete_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cat1',
            field=models.CharField(choices=[('style', 'style'), ('life', 'life'), ('entertainment', 'entertainment'), ('food', 'food')], default='style', max_length=15),
        ),
    ]
