# Generated by Django 2.2.6 on 2020-01-21 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_cat1'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cat2',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
