# Generated by Django 2.2.6 on 2020-03-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_cat2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cat1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='cat2',
        ),
        migrations.AddField(
            model_name='post',
            name='icon',
            field=models.FileField(default=0, upload_to='static/uploads'),
            preserve_default=False,
        ),
    ]
